import { PaymentDashboardData } from '@/types/payment';
import { LoanDetailData } from '@/types/loan';

export const TODAY_STR = '2026-08-20';

export const MOCK_DASHBOARD_TODAY: PaymentDashboardData = {
  metadata: {
    targetDate: TODAY_STR,
    serverToday: TODAY_STR,
  },
  dueToday: [
    {
      installmentId: 'inst-101',
      installmentNumber: 2,
      loanId: 'uuid-loan-1',
      clientId: 'cli-1',
      clientName: 'María Quispe Mamani',
      clientPhone: '71234567',
      dueDate: TODAY_STR,
      totalAmount: 500,
      paidAmount: 0,
      remainingAmount: 500,
      status: 'PENDING',
      daysOverdue: 0,
      paidAt: null,
      scheduledTime: '09:30',
    },
    {
      installmentId: 'inst-102',
      installmentNumber: 3,
      loanId: 'uuid-loan-2',
      clientId: 'cli-2',
      clientName: 'Juan Carlos Mamani',
      clientPhone: '61234567',
      dueDate: TODAY_STR,
      totalAmount: 400,
      paidAmount: 0,
      remainingAmount: 400,
      status: 'PENDING',
      daysOverdue: 0,
      paidAt: null,
      scheduledTime: '10:15',
    },
    {
      installmentId: 'inst-103',
      installmentNumber: 1,
      loanId: 'uuid-loan-3',
      clientId: 'cli-3',
      clientName: 'Roberto Choque',
      clientPhone: '78881234',
      dueDate: TODAY_STR,
      totalAmount: 600,
      paidAmount: 200,
      remainingAmount: 400,
      status: 'PARTIAL',
      daysOverdue: 0,
      paidAt: null,
      scheduledTime: '14:00',
    },
    {
      installmentId: 'inst-104',
      installmentNumber: 4,
      loanId: 'uuid-loan-4',
      clientId: 'cli-4',
      clientName: 'Ana Condori',
      clientPhone: '72223344',
      dueDate: TODAY_STR,
      totalAmount: 420,
      paidAmount: 0,
      remainingAmount: 420,
      status: 'PENDING',
      daysOverdue: 0,
      paidAt: null,
      scheduledTime: '16:30',
    },
  ],
  overdue: [
    {
      installmentId: 'inst-201',
      installmentNumber: 1,
      loanId: 'uuid-loan-5',
      clientId: 'cli-5',
      clientName: 'Lucía Vargas',
      clientPhone: '77711223',
      dueDate: '2026-08-10',
      totalAmount: 280,
      paidAmount: 0,
      remainingAmount: 280,
      status: 'OVERDUE',
      daysOverdue: 10,
      paidAt: null,
      scheduledTime: '08:00',
    },
    {
      installmentId: 'inst-202',
      installmentNumber: 2,
      loanId: 'uuid-loan-6',
      clientId: 'cli-6',
      clientName: 'Pedro Flores',
      clientPhone: '69998877',
      dueDate: '2026-08-14',
      totalAmount: 540,
      paidAmount: 0,
      remainingAmount: 540,
      status: 'OVERDUE',
      daysOverdue: 6,
      paidAt: null,
      scheduledTime: '11:00',
    },
  ],
  paidToday: [
    {
      installmentId: 'inst-301',
      installmentNumber: 3,
      loanId: 'uuid-loan-7',
      clientId: 'cli-7',
      clientName: 'Carlos Roca',
      clientPhone: '75551234',
      dueDate: TODAY_STR,
      totalAmount: 350,
      paidAmount: 350,
      remainingAmount: 0,
      status: 'PAID',
      daysOverdue: 0,
      paidAt: `${TODAY_STR}T11:20:00.000Z`,
      scheduledTime: '09:00',
    },
  ],
};

export const MOCK_LOAN_DETAILS_MAP: Record<string, LoanDetailData> = {
  'uuid-loan-1': {
    loan: {
      id: 'uuid-loan-1',
      clientId: 'cli-1',
      clientName: 'María Quispe Mamani',
      clientIdNumber: '9988771-LP',
      createdBy: 'admin',
      currency: 'BOB',
      mode: 'automatic',
      capitalAmount: 2000,
      interestRate: 10,
      periodType: 'monthly',
      totalInstallments: 5,
      totalAmount: 2500,
      totalPaid: 1000,
      outstandingBalance: 1500,
      status: 'ACTIVE',
      startDate: '2026-07-20T00:00:00.000Z',
      firstDueDate: '2026-08-20',
      notes: 'Préstamo comercial',
      createdAt: '2026-07-20T00:00:00.000Z',
    },
    installments: [
      {
        id: 'inst-100',
        installmentNumber: 1,
        dueDate: '2026-07-20',
        capitalAmount: 400,
        interestAmount: 100,
        totalAmount: 500,
        paidAmount: 500,
        remainingAmount: 0,
        daysOverdue: 0,
        status: 'PAID',
        paidAt: '2026-07-20T10:00:00.000Z',
      },
      {
        id: 'inst-101',
        installmentNumber: 2,
        dueDate: TODAY_STR,
        capitalAmount: 400,
        interestAmount: 100,
        totalAmount: 500,
        paidAmount: 0,
        remainingAmount: 500,
        daysOverdue: 0,
        status: 'PENDING',
        paidAt: null,
      },
      {
        id: 'inst-101b',
        installmentNumber: 3,
        dueDate: '2026-09-20',
        capitalAmount: 400,
        interestAmount: 100,
        totalAmount: 500,
        paidAmount: 0,
        remainingAmount: 500,
        daysOverdue: 0,
        status: 'PENDING',
        paidAt: null,
      },
      {
        id: 'inst-101c',
        installmentNumber: 4,
        dueDate: '2026-10-20',
        capitalAmount: 400,
        interestAmount: 100,
        totalAmount: 500,
        paidAmount: 0,
        remainingAmount: 500,
        daysOverdue: 0,
        status: 'PENDING',
        paidAt: null,
      },
      {
        id: 'inst-101d',
        installmentNumber: 5,
        dueDate: '2026-11-20',
        capitalAmount: 400,
        interestAmount: 100,
        totalAmount: 500,
        paidAmount: 0,
        remainingAmount: 500,
        daysOverdue: 0,
        status: 'PENDING',
        paidAt: null,
      },
    ],
    guarantees: [
      {
        linkId: 'link-1',
        id: 'guar-1',
        type: 'VEHICLE',
        description: 'Motocicleta Suzuki AX100 Color Rojo',
        estimatedValue: 1200,
        status: 'IN_USE',
      },
    ],
    payments: [
      {
        id: 'pay-1',
        amount: 500,
        method: 'cash',
        paymentDate: '2026-07-20',
        notes: 'Pago primera cuota',
        voided: false,
        voidedAt: null,
        voidReason: null,
        createdAt: '2026-07-20T10:00:00.000Z',
      },
    ],
  },
  'uuid-loan-2': {
    loan: {
      id: 'uuid-loan-2',
      clientId: 'cli-2',
      clientName: 'Juan Carlos Mamani',
      clientIdNumber: '4455667-CB',
      createdBy: 'admin',
      currency: 'BOB',
      mode: 'automatic',
      capitalAmount: 1500,
      interestRate: 10,
      periodType: 'monthly',
      totalInstallments: 4,
      totalAmount: 1800,
      totalPaid: 400,
      outstandingBalance: 1400,
      status: 'ACTIVE',
      startDate: '2026-06-18T00:00:00.000Z',
      firstDueDate: '2026-07-18',
      notes: 'Préstamo personal',
      createdAt: '2026-06-18T00:00:00.000Z',
    },
    installments: [
      {
        id: 'inst-200',
        installmentNumber: 1,
        dueDate: '2026-07-18',
        capitalAmount: 350,
        interestAmount: 100,
        totalAmount: 450,
        paidAmount: 450,
        remainingAmount: 0,
        daysOverdue: 0,
        status: 'PAID',
        paidAt: '2026-07-18T14:30:00.000Z',
      },
      {
        id: 'inst-201-loan2',
        installmentNumber: 2,
        dueDate: '2026-08-05',
        capitalAmount: 400,
        interestAmount: 100,
        totalAmount: 500,
        paidAmount: 0,
        remainingAmount: 500,
        daysOverdue: 15,
        status: 'OVERDUE',
        paidAt: null,
      },
      {
        id: 'inst-102',
        installmentNumber: 3,
        dueDate: TODAY_STR,
        capitalAmount: 400,
        interestAmount: 100,
        totalAmount: 500,
        paidAmount: 0,
        remainingAmount: 500,
        daysOverdue: 0,
        status: 'PENDING',
        paidAt: null,
      },
      {
        id: 'inst-203',
        installmentNumber: 4,
        dueDate: '2026-09-20',
        capitalAmount: 400,
        interestAmount: 100,
        totalAmount: 500,
        paidAmount: 0,
        remainingAmount: 500,
        daysOverdue: 0,
        status: 'PENDING',
        paidAt: null,
      },
    ],
    guarantees: [],
    payments: [
      {
        id: 'pay-2',
        amount: 450,
        method: 'transfer',
        paymentDate: '2026-07-18',
        notes: 'Transferencia BNB',
        voided: false,
        voidedAt: null,
        voidReason: null,
        createdAt: '2026-07-18T14:30:00.000Z',
      },
    ],
  },
};

